// =============================================================================
// A short Ogg Vorbis stream for audioDiagnostics: 10000 frames of 8 kHz
// stereo (a 440 Hz tone on the left, 660 Hz on the right), encoded with
// libvorbisenc at quality -0.1. The last page's granule position states the
// stream length (10000). 4036 bytes, stored as base64.
// =============================================================================

#include <vector>

namespace {

const char* const kVorbisToneBase64 =
    "T2dnUwACAAAAAAAAAAABAAAAAAAAAImS/cUBHgF2b3JiaXMAAAAAAkAfAAAAAAAA4C4AAAAAAACZ"
    "AU9nZ1MAAAAAAAAAAAAAAQAAAAEAAADiceBlDET/////////////GwN2b3JiaXM0AAAAWGlwaC5P"
    "cmcgbGliVm9yYmlzIEkgMjAyMDA3MDQgKFJlZHVjaW5nIEVudmlyb25tZW50KQAAAAABBXZvcmJp"
    "cxFCQ1YBAAABAAxSFCElGVNKYwiVUlIpBR1jUFtHHWPUOUYhZBBTiEkZpXtPKpVYSsgRUlgpRR1T"
    "TFNJlVKWKUUdYxRTSCFT1jFloXMUS4ZJCSVsTa50FkvomWOWMUYdY85aSp1j1jFFHWNSUkmhcxg6"
    "ZiVkFDpGxehifDA6laJCKL7H3lLpLYWKW4q91xpT6y2EGEtpwQhhc+211dxKasUYY4wxxsXiUyiC"
    "0JBVAAABAABABAFCQ1YBAAoAAMJQDEVRgNCQVQBABgCAABRFcRTHcRxHkiTLAkJDVgEAQAAAAgAA"
    "KI7hKJIjSZJkWZZlWZameZaouaov+64u667t6roOhIasBADIAAAYJJpUzEGJhEgMKeYoCCGEEEII"
    "zYAFlZOWUwaiUgxSrgxYyiBHvVLgKaQg9g6CCp2jGEQLusYWa3A5CCGED0IQGrJCAAjNADBIDiBp"
    "GiBpGgAAAAAAAABIngdonghonggAAAAAAAAAkucBmigCmugBAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACB5HuCZJuCJIgAA"
    "AAAAAABopgh4ogqIqgoAAAAAAAAAmmgComoCoqoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACB5HuCJIuCJJgAAAAAAAABo"
    "ogiIqgqIpgoAAAAAAAAAmmgCoqoCnioCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAIAAAIcAAACLAQCg1ZEQDECQAYHMeyAADAkSxNAwAAR5I0DQAALE3zPAAAsDTN"
    "8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAABAAADDgAAASYUAYKDVkJAEQBABgMRdMAlgWwLICmATQN4HkA0QOYJgAQAABQ4AAA"
    "EGCDpsTiAIWGrAQAogAADIoiSZrledA0TfM8aJqmeSI8z/NEEZ7neaIIUfQ804Qoep5pwjRF0TSB"
    "KJqmAACAAgcAgAAbNCUWByg0ZCUAEBIAYFAUy/I8UfQ8UzRNVYWmeZ4oiqJpqqrqQtM8TxRF0TRV"
    "1VXheaJomqJomqrquvA8UTRNUVRNVXVdiKIomqZpqqrqui5EURRN0zRV1XVlGaZpmqpqmqrqurIM"
    "TNFUTVNVXVeWgSiaoqm6rizbMhBF0TRNVZVdWQamaZqq6rqybNsA01RV15Vl2Qaoqqq6rmzbNkBV"
    "VdV1ZdmWAarqurJs27YNwHVdV5ZtWwAAwIEDAECAEXSSUWURNppw4QEoNGRFABAFAAAYw5RiShnG"
    "KJQWSsOYlJJCqKik1FJKlZSUWiqlgpJSSqVkklpKLbUKQgkhlVJBKKWkUgoAADtwAAA7sBAKDVkJ"
    "AOQBAACEKOUchBBKKRlzDkIIpYSMOQchhFJK5yCEEEIppXMQQuiglNI5CKGUUkoJIYQQSkklhRBC"
    "KaWklEoJoZQSUimllBJCKSmVUkIIpZQCAIAKHAAAAmwU2ZxgJKjQkJUAQCoAgMFxNEvTNM3zRFGz"
    "LE3zPE3zRNPULEvTPE3TRNF0eZ7neaLniaJp8jzP80RPFEXVRBY9URRF01RVMlEURVFUTVWFJ5qi"
    "acqq68ITRdE0ZdeV4TJNVzVV14Usm6apumRAVrmuK7uALKuyrLoCAMATHACACmxYHeGkaCyw0JCV"
    "AEAGAABADEJMKYUYY0oxxpRijCklAABgwAEAIMCEMlBoyIoAIAoAAHDOOeecc84555xzzjnnnHPO"
    "OeecY4wxxhhjjDHGGGOMMcYYY4wxxhhjjDHGGGOMMcYYEwCwE+EAsBNhIRQashIACAcAAIxBSDpK"
    "KaWUUqUUU1RSSimllDKklHKMUkoppZQy5xyElFJKKaUUOuYgpZRSSimlVFJKKaWUUkoppVRSSiml"
    "lFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRS"
    "SimllFJKKaWUUkoppZRSSimllFJKBQCYPDgAQCXYOMNK0lnhaHChISsBgNwAAAAhxhxzTkoIpZSU"
    "SkuttdA55xyUUkpKqaTUWmqdY8xBKSWUEkpJKaWUQgihg1JSKSm1UlpLqYRQOiilhFJSKqmU0loL"
    "JZQQSkkppVJKaqmlVlJJoYQSSgmlpJJSSi2FUkpJKaVUUkqptNJaaqWkElJJoaRSSkoptVZCSCW0"
    "VFpLKaWSUkulhVRSKamkUEpJLaWWSkkplNJKKqWEUkoJpaSUUkullJJSSSmk0kpLJZVSUikplVRK"
    "KSm1UkoqqaWSSkmptBJKSSmVVkpKqZRUSkkllZZSKaWVkkJJKZWSSgkptZZaSimlFEoqrZRSUimp"
    "lFZKKSW0UkppIZWSSmultVZKKaGkUlopLZVUSkullZJCKqGEUgAA0IEDAECAEZUWYqcZVx6BIwoZ"
    "JqAAAAAQABBgAggMEBSMQhAgjIAAAAAAAGAAwAcAQFIABEREM2dwgJCgsMDQ4PAAEQEAAAggAAAA"
    "AAAAAACAT2dnUwAEECcAAAAAAAABAAAAAgAAAISQZfopIh0cHh8fHh0cHx8eHR8bHRwdHR8cHB4f"
    "Hh4dHB4fHx4dHB8fHh0fJR22npnTRTUcCf8xwfefqofrnAAAJBVtXH000+sAXD376CEAup+Zc6es"
    "OEL+YwTA1ef4DaD9FAAAAKSYEgA8zwO6n5ltlRVHyH+MAPA5fgPoPgUAAAAhBIBnuh8Aup+Zc6es"
    "OEL+YwTA5eeoh7sCAAAgn+/5A8DrD78Fup+Zc6esOEL+YwQw+/xyoR7uEgAAAA+bOwC8fvYtALqf"
    "mXOnrDhC/mMEMPtjC78BdJ8AAAAAj8cNgGm8bwC6n5lzp6w4Qv5jBDD7/GrhN4D2EwAAAODBXQC4"
    "nxu6n5lzp6w4Qv5jBMDlT6iHqwQAAKA+3/0XAFf9BLqfmW2VFUfIf4wA8BPq4aoAAAAoPgqA1/77"
    "CQC6n5lzp6w4Qv5jBMDVT/gN4ODTDgAAAKqMYwqA3/cAup+Zc6esOEL+YwTATy/xG0D3WwAAAOB3"
    "318B8H0eALqfmbNTVhwh/zECWPy0zNTDXQEAAOC2vR8AHBy8BrqfmbNTVhwh/zEC4Kd5ph5uAAAA"
    "+PkeAPx09VsAup+Zc6esOEL+Y4K/9hvA4SctAAAAOPPxf6cBwP/fALqfmW2VFUfIf4wAWD7HbwB+"
    "BwAAACmjBAC/G7qfmXOnrDhC/mMEwPw56uEqAQAASHwqAMz47esBup+Zc6esOEL+Y4K3Vg8XAAAA"
    "nPrvo7MA8K2fALqfmbNTVhwh/zECmH0+L9TDVQEAAODBDQA/vX4Aup+Zs1NWHCH/MQKYfb4s/Abg"
    "twAAAMBj4waAzwO6n5lzp6w4Qv5jBMCLl/gN4PDTFgAAAHy+8S8AfNsHup+Zc6esOEL+YwTA/BPq"
    "4QYAAEDFpwqAnw6+BbqfmW2VFUfIf4wAWH5CPdwlAAAAxUgBcHD1NQC6n5lzp6w4Qv5jBMDLl/gN"
    "oPsdAAAA+I3/VwB8vxu6n5mzU1YcIf8xAuCnq5nfAA4+6QAAAMDP/QBg67sBup+Zc6esOEL+YwSw"
    "+MlMPVwAAABw+78HAN9++xMAup+Zc6esOEL+YwTAT5eoh6sCAADA7/6+AHB1pp8Aup+Zc6esOEL+"
    "YwTA1ef4DaD9FAAAAKSYEgA8zwO6n5ltlRVHyH+MAPA5fgPoPgUAAAAhBIBnuh8Aup+Zc6esOEL+"
    "YwTA5eeoh7sCAAAgn+/5A8DrD78Fup+Zc6esOEL+YwQw+/xyoR7uEgAAAA+bOwC8fvYtALqfmXOn"
    "rDhC/mMEMPtjC78BdJ8AAAAAj8cNgGm8bwC6n5lzp6w4Qv5jBDD7/GrhN4D2EwAAAODBXQC4nxu6"
    "n5lzp6w4Qv5jBMDlT6iHqwQAAKA+3/0XAFf9BLqfmW2VFUfIf4wA8BPq4aoAAAAoPgqA1/77CQC6"
    "n5lzp6w4Qv5jBMDVT/gN4ODTDgAAAKqMYwqA3/cAup+Zc6esOEL+YwTATy/xG0D3WwAAAOB3318B"
    "8H0eALqfmbNTVhwh/zECWPy0zNTDXQEAAOC2vR8AHBy8BrqfmbNTVhwh/zEC4Kd5ph5uAAAA+Pke"
    "APx09VsAup+Zc6esOEL+Y4K/9hvA4SctAAAAOPPxf6cBwP/fALLVUHitGo6E/8QALFefL/wG0H3S"
    "AQCAqqQqX93b6Qbg2WwBVgGOz5NAiL4i826wGSb4rtYAAABNPv5p3/8BkL7fAg==";

} // namespace

std::vector<char> vorbisToneBytes() {
    auto value = [](char c) -> int {
        if (c >= 'A' && c <= 'Z') return c - 'A';
        if (c >= 'a' && c <= 'z') return c - 'a' + 26;
        if (c >= '0' && c <= '9') return c - '0' + 52;
        if (c == '+') return 62;
        if (c == '/') return 63;
        return -1;
    };
    std::vector<char> out;
    unsigned int bits = 0;
    int count = 0;
    for (const char* p = kVorbisToneBase64; *p; ++p) {
        const int v = value(*p);
        if (v < 0) continue;   // padding
        bits = (bits << 6) | (unsigned int)v;
        count += 6;
        if (count >= 8) {
            count -= 8;
            out.push_back((char)((bits >> count) & 0xFF));
        }
    }
    return out;
}
